version: '3.7'

services:
  web:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webapp/:/code/
    ports:
      - 8000:8000
    env_file:
      - ./env/dev.env
      - ./env/civicrm.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/dev.env

volumes:
  postgres_data:
